SUBJECT47_PROPS 3
LEVEL:TANK_CLUSTER,10,0,23,0
LEVEL:CEILING_LIGHT,8,5,18,0
LEVEL:ANALYZER_STATION,26,0,21,0
LEVEL:ANALYZER_STATION,37,0,21,0
LEVEL:LAB_BENCH,33,0,10,0
LEVEL:CEILING_LIGHT,36,5,20,0
LEVEL:STORAGE_CRATE,17,0,24,0
LEVEL:CEILING_LIGHT,31,5,10,0
LEVEL:SERVER_RACK,23,1,25,0
LEVEL:CEILING_LIGHT,16,5,22,0
LEVEL:LAB_BENCH,29,0,10,0
LEVEL:CEILING_LIGHT,28,5,20,0
LEVEL:CEILING_LIGHT,12,5,20,0
LEVEL:SERVER_RACK,20,1,25,0
