SUBJECT47_PROPS 3
LEVEL:CONTAINMENT_POD,39,0,27,0
LEVEL:ANALYZER_STATION,42,0,22,0
LEVEL:SERVER_RACK,35,1,28,0
LEVEL:CEILING_LIGHT,40,5,24,0
LEVEL:LAB_BENCH,36,0,20,0
LEVEL:TANK_CLUSTER,37,0,30,0
LEVEL:LAB_BENCH,45,0,20,0
LEVEL:CEILING_LIGHT,36,5,24,0
LEVEL:STORAGE_CRATE,44,0,29,0
LEVEL:CEILING_LIGHT,44,5,24,0
LEVEL:CEILING_LIGHT,38,5,28,0
